export const allClassNames = [
  "Adele",
  "Angelic Buster",
  "Aran",
  "Mage (Fire/Poison)",
  "Mage (Ice/Lightning)",
  "Ark",
  "Battle Mage",
  "Beast Tamer",
  "Bishop",
  "Blaster",
  "Blaze Wizard",
  "Bowmaster",
  "Buccanner",
  "Cadena",
  "Cannoneer",
  "Corsair",
  "Dark Night",
  "Dawn Warrior",
  "Demon Avenger",
  "Demon Slayer",
  "Dual Blade",
  "Evan",
  "Hayato",
  "Hero",
  "Hoyoung",
  "Illium",
  "Jett",
  "Kain",
  "Kaiser",
  "Kanna",
  "Kinesis",
  "Lara",
  "Luminous",
  "Marksman",
  "Mechanic",
  "Mercedes",
  "Mihile",
  "Night Lord",
  "Night Walker",
  "Paladin",
  "Pathfinder",
  "Phantom",
  "Shade",
  "Shadower",
  "Thunder Breaker",
  "Wild Hunter",
  "Wind Archer",
  "Xenon",
  "Zero",
] as const

export type ClassName = typeof allClassNames[number]

export const allClassTypes = [
  "Warrior",
  "Bowman",
  "Magician",
  "Thief",
  "Pirate",
  "Xenon",
] as const

export type ClassType = typeof allClassTypes[number]

export const allClassLinkNames = [
  "Adventurer's Curiosity",
  "Bravado",
  "Close Call",
  "Combo Kill Blessing",
  "Core Aura",
  "Cygnus' Blessing",
  "Elementalism",
  "Elven Blessing",
  "Empirical Knowledge",
  "Focus Spirit",
  "Fury Unleashed",
  "Hybrid Logic",
  "Invincible Belief",
  "Iron Will",
  "Judgement",
  "Keen Edge",
  "Knight's Watch",
  "Light Wash",
  "Nature's Friend",
  "Phantom Instinct",
  "Pirate Blessing",
  "Rhinne's Blessing",
  "Rune Persistence",
  "Solus",
  "Spirit of Freedom",
  "Terms and Conditions",
  "Thief's Cunning",
  "Tide of Battle",
  "Time to Prepare",
  "Unfair Advantage",
  "Wild Rage",
] as const

export type ClassLinkName = typeof allClassLinkNames[number]
